### ISSUE TITLE
Wrapper Ads Support

### ISSUE THREAD

**Issue by stuffmc** [denivip/ios-vast-player#3]
I'm about to start working on it, if you can't — but I prefer to open this issue as a good communication instead of adding this to the Pull Request. I'd love to have a few things clarified. The first one being if simply taking the URL in `<VASTAdTagURI>` and "calling" a regular ad with this URL would be "enough". I'm guessing not really since the Wrapper XML contains much more infos, but at least the video playing part seems to work.

**Comment by kolyuchiy** [comment]
1) In theory one Wrapper ad can wrap another wrapper recursively.
2) All the additional elements of Wrapper ad are needed to send impressions. You must gather all impression URLs from wrappers chain including the last leaf ad and send impression events to all of them.

To learn more just read [VAST spec](http://www.iab.net/vast). It's not very long and is easy to read and understand.

**Comment by stuffmc** [comment]
Anyone looking for that support could either look at https://github.com/stuffmc/ios-vast-player/tree/vast2 (some of it has been merged in master here).
